//------------------------------------------------------------------------------
// Copyright (c) 2005, 2006 IBM Corporation and others.
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Eclipse Public License v1.0
// which accompanies this distribution, and is available at
// http://www.eclipse.org/legal/epl-v10.html
// 
// Contributors:
// IBM Corporation - initial implementation
//------------------------------------------------------------------------------

// This file will include dynamically generated process layout related data from 
// the publishing service 
contentPage.processPage.imageFiles["_KljuYZX7Eea5INDw8_iX4wActivity"]="./../../Enutri/deliveryprocesses/resources/Ciclo de Vida_D6739670_d6739670_Activity.jpeg"
contentPage.processPage.imageFiles["_KljuYZX7Eea5INDw8_iX4w,_T3pk0ZX7Eea5INDw8_iX4w,_dNIGcZX7Eea5INDw8_iX4w,_Q0obwZYnEeaRb6mrVBIJLAActivity"]="./../../Enutri/deliveryprocesses/resources/Planejar e Gerenciar a Iteração_23D37275_c00d270a_Activity.jpeg"
contentPage.processPage.imageFiles["_KljuYZX7Eea5INDw8_iX4w,_TPexkZX7Eea5INDw8_iX4w,_5QfqkZX7Eea5INDw8_iX4w,_WythkZYYEeaEjfH4fvjAEAActivity"]="./../../Enutri/deliveryprocesses/resources/Manter Tarefas Contínuas_CF539AB3_5a756c79_Activity.jpeg"
contentPage.processPage.imageFiles["_KljuYZX7Eea5INDw8_iX4w,_U11rYZX7Eea5INDw8_iX4w,_XkzzEZX7Eea5INDw8_iX4w,_6VlmYZYnEeaRb6mrVBIJLAActivity"]="./../../Enutri/deliveryprocesses/resources/Planejar e Gerenciar a Iteração_E8C16562_5016d69a_Activity.jpeg"
contentPage.processPage.imageFiles["_KljuYZX7Eea5INDw8_iX4w,_TPexkZX7Eea5INDw8_iX4w,_4ATOAZX7Eea5INDw8_iX4w,_XOL8oZYYEeaEjfH4fvjAEAActivity"]="./../../Enutri/deliveryprocesses/resources/Manter Tarefas Contínuas_95CCC39C_5f800a4d_Activity.jpeg"
contentPage.processPage.imageFiles["_KljuYZX7Eea5INDw8_iX4w,_SWNAMZX7Eea5INDw8_iX4w,_9MPHYZX7Eea5INDw8_iX4w,_T8rZUZX8Eea5INDw8_iX4wActivity"]="./../../Enutri/deliveryprocesses/resources/Gerenciar a Iteração_D5BF8D35_89a85978_Activity.jpeg"
contentPage.processPage.imageFiles["_KljuYZX7Eea5INDw8_iX4w,_U11rYZX7Eea5INDw8_iX4w,_XkzzEZX7Eea5INDw8_iX4w,_6VlmZZYnEeaRb6mrVBIJLAActivity"]="./../../Enutri/deliveryprocesses/resources/Treinar Usuários_AD534781_14a8b8b9_Activity.jpeg"
contentPage.processPage.imageFiles["_KljuYZX7Eea5INDw8_iX4w,_SWNAMZX7Eea5INDw8_iX4w,_9MPHYZX7Eea5INDw8_iX4w,_8g_VgZX8Eea5INDw8_iX4wActivity"]="./../../Enutri/deliveryprocesses/resources/Gerenciar Requisitos_D9C9AC9D_8db278e0_Activity.jpeg"
contentPage.processPage.imageFiles["_KljuYZX7Eea5INDw8_iX4w,_TPexkZX7Eea5INDw8_iX4w,_6iCK8ZX7Eea5INDw8_iX4w,_Csus85YnEeaRb6mrVBIJLAActivity"]="./../../Enutri/deliveryprocesses/resources/Realizar Tarefas Contínuas_223346CB_beac7478_Activity.jpeg"
contentPage.processPage.imageFiles["_KljuYZX7Eea5INDw8_iX4w,_U11rYZX7Eea5INDw8_iX4w,_WVEpgZX7Eea5INDw8_iX4w,_yzrUIZYnEeaRb6mrVBIJLAActivity"]="./../../Enutri/deliveryprocesses/resources/Planejar e Gerenciar a Iteração_BFF77D55_6a965642_Activity.jpeg"
contentPage.processPage.imageFiles["_KljuYZX7Eea5INDw8_iX4w,_U11rYZX7Eea5INDw8_iX4w,_WVEpgZX7Eea5INDw8_iX4w,_yzrUI5YnEeaRb6mrVBIJLAActivity"]="./../../Enutri/deliveryprocesses/resources/Realizar Tarefas Contínuas_176A6730_c209401d_Activity.jpeg"
contentPage.processPage.imageFiles["_KljuYZX7Eea5INDw8_iX4w,_SWNAMZX7Eea5INDw8_iX4w,_9MPHYZX7Eea5INDw8_iX4wActivity"]="./../../Enutri/deliveryprocesses/resources/Iteração de Elaboração E1..En_2D23C810_4d7a5aef_Activity.jpeg"
contentPage.processPage.imageFiles["_KljuYZX7Eea5INDw8_iX4w,_SWNAMZX7Eea5INDw8_iX4w,_9MPHYZX7Eea5INDw8_iX4w,_9S-zIZX8Eea5INDw8_iX4wActivity"]="./../../Enutri/deliveryprocesses/resources/Iniciar o Projeto_99D9A1C_bd86665f_Activity.jpeg"
contentPage.processPage.imageFiles["_KljuYZX7Eea5INDw8_iX4w,_TPexkZX7Eea5INDw8_iX4w,_6iCK8ZX7Eea5INDw8_iX4w,_Csus8ZYnEeaRb6mrVBIJLAActivity"]="./../../Enutri/deliveryprocesses/resources/Planejar e Gerenciar a Iteração_CAC05CF0_67398a9d_Activity.jpeg"
contentPage.processPage.imageFiles["_KljuYZX7Eea5INDw8_iX4w,_TPexkZX7Eea5INDw8_iX4w,_25ftQZYXEeaEjfH4fvjAEA,_Dc2iUZYnEeaRb6mrVBIJLAActivity"]="./../../Enutri/deliveryprocesses/resources/Planejar e Gerenciar a Iteração_243A709B_68c8b06f_Activity.jpeg"
contentPage.processPage.imageFiles["_KljuYZX7Eea5INDw8_iX4w,_TPexkZX7Eea5INDw8_iX4w,_7tUSUZX7Eea5INDw8_iX4w,_HFKs05YnEeaRb6mrVBIJLAActivity"]="./../../Enutri/deliveryprocesses/resources/Realizar Tarefas Contínuas_66D087AB_16cb81bb_Activity.jpeg"
contentPage.processPage.imageFiles["_KljuYZX7Eea5INDw8_iX4w,_TPexkZX7Eea5INDw8_iX4w,_25ftQZYXEeaEjfH4fvjAEA,_Dc2iU5YnEeaRb6mrVBIJLAActivity"]="./../../Enutri/deliveryprocesses/resources/Realizar Tarefas Contínuas_7BAD5A76_c03b9a4a_Activity.jpeg"
contentPage.processPage.imageFiles["_KljuYZX7Eea5INDw8_iX4w,_T3pk0ZX7Eea5INDw8_iX4w,_dNIGcZX7Eea5INDw8_iX4w,_OkY3cZYnEeaRb6mrVBIJLA,_Q0obw5YnEeaRb6mrVBIJLAActivity"]="./../../Enutri/deliveryprocesses/resources/Realizar Tarefas Contínuas_7B465C50_bf174226_Activity.jpeg"
contentPage.processPage.imageFiles["_KljuYZX7Eea5INDw8_iX4w,_TPexkZX7Eea5INDw8_iX4w,_5QfqkZX7Eea5INDw8_iX4w,_81LBgZYXEeaEjfH4fvjAEAActivity"]="./../../Enutri/deliveryprocesses/resources/Gerenciar a Iteração_D56600EF_6087d2b5_Activity.jpeg"
contentPage.processPage.imageFiles["_KljuYZX7Eea5INDw8_iX4w,_TPexkZX7Eea5INDw8_iX4w,_4ATOAZX7Eea5INDw8_iX4w,_DWQv8ZYYEeaEjfH4fvjAEAActivity"]="./../../Enutri/deliveryprocesses/resources/Gerenciar a Iteração_92372328_5bea69d9_Activity.jpeg"
contentPage.processPage.imageFiles["_KljuYZX7Eea5INDw8_iX4w,_T3pk0ZX7Eea5INDw8_iX4w,_dNIGcZX7Eea5INDw8_iX4w,_1o_1UZfxEeaGraIkjYaOmAActivity"]="./../../Enutri/deliveryprocesses/resources/Realizar Tarefas Contínuas_4C5CF38E_e896a823_Activity.jpeg"
contentPage.processPage.imageFiles["_KljuYZX7Eea5INDw8_iX4w,_TPexkZX7Eea5INDw8_iX4w,_7tUSUZX7Eea5INDw8_iX4w,_HFKs0ZYnEeaRb6mrVBIJLAActivity"]="./../../Enutri/deliveryprocesses/resources/Planejar e Gerenciar a Iteração_F5D9DD0_bf5897e0_Activity.jpeg"
contentPage.processPage.imageFiles["_KljuYZX7Eea5INDw8_iX4w,_TPexkZX7Eea5INDw8_iX4w,_5QfqkZX7Eea5INDw8_iX4w,_-jchMZYXEeaEjfH4fvjAEAActivity"]="./../../Enutri/deliveryprocesses/resources/Gerenciar os Requisitos_3BB973DC_c6db45a2_Activity.jpeg"
contentPage.processPage.imageFiles["_KljuYZX7Eea5INDw8_iX4w,_SWNAMZX7Eea5INDw8_iX4w,_9MPHYZX7Eea5INDw8_iX4w,_9-3owZX8Eea5INDw8_iX4wActivity"]="./../../Enutri/deliveryprocesses/resources/Desenvolver a Arquitetura_14989D77_c88169ba_Activity.jpeg"
contentPage.processPage.imageFiles["_KljuYZX7Eea5INDw8_iX4w,_U11rYZX7Eea5INDw8_iX4w,_XkzzEZX7Eea5INDw8_iX4w,_6VlmY5YnEeaRb6mrVBIJLAActivity"]="./../../Enutri/deliveryprocesses/resources/Realizar Tarefas Contínuas_40344F3D_a789c075_Activity.jpeg"
contentPage.processPage.imageFiles["_KljuYZX7Eea5INDw8_iX4w,_TPexkZX7Eea5INDw8_iX4wActivity"]="./../../Enutri/deliveryprocesses/resources/Concepção_E5842781_c57bfc45_Activity.jpeg"
contentPage.processPage.elementUrls["_fBMPoJX8Eea5INDw8_iX4w_moV8UJX-Eea5INDw8_iX4w"] = ["Analista","Enutri/capabilitypatterns/analista_32361394.html"];
contentPage.processPage.elementUrls["_znWwopYjEeaRb6mrVBIJLA"] = ["Stakeholder","Enutri/capabilitypatterns/stakeholder_46B41131.html"];
contentPage.processPage.elementUrls["_fBMPoJX8Eea5INDw8_iX4w_toEHgJX-Eea5INDw8_iX4w"] = ["Stakeholder","Enutri/capabilitypatterns/stakeholder_2B06F3DC.html"];
contentPage.processPage.elementUrls["_Q0obw5YnEeaRb6mrVBIJLA"] = ["Realizar Tarefas Contínuas","Enutri/deliveryprocesses/Realizar Tarefas Contínuas_7B465C50.html"];
contentPage.processPage.elementUrls["_ZFnw4JfwEeaGraIkjYaOmA"] = ["Desenvolvedor","Enutri/capabilitypatterns/desenvolvedor_E7135F63.html"];
contentPage.processPage.elementUrls["_8g_VgZX8Eea5INDw8_iX4w"] = ["Gerenciar os Requisitos","Enutri/deliveryprocesses/Gerenciar Requisitos_D9C9AC9D.html"];
contentPage.processPage.elementUrls["_haGrIJYlEeaRb6mrVBIJLA"] = ["Gerente do projeto","Enutri/capabilitypatterns/gerente_3BEF7B83.html"];
contentPage.processPage.elementUrls["_6VlmYZYnEeaRb6mrVBIJLA"] = ["Planejar e Gerenciar a Iteração","Enutri/deliveryprocesses/Planejar e Gerenciar a Iteração_E8C16562.html"];
contentPage.processPage.elementUrls["_2SjlIpfwEeaGraIkjYaOmA"] = ["Banco de Dados de Testes","Enutri/capabilitypatterns/db_testes_2A47A202.html"];
contentPage.processPage.elementUrls["_50vVMJX9Eea5INDw8_iX4w_pXuTsJX-Eea5INDw8_iX4w"] = ["Desenvolvedor","Enutri/capabilitypatterns/desenvolvedor_82DF99DA.html"];
contentPage.processPage.elementUrls["_HFKs0ZYnEeaRb6mrVBIJLA"] = ["Planejar e Gerenciar a Iteração","Enutri/deliveryprocesses/Planejar e Gerenciar a Iteração_F5D9DD0.html"];
contentPage.processPage.elementUrls["_znprkJYjEeaRb6mrVBIJLA"] = ["Arquiteto","Enutri/capabilitypatterns/arquiteto_D5AF9B11.html"];
contentPage.processPage.elementUrls["_haGrKpYlEeaRb6mrVBIJLA"] = ["Testador","Enutri/capabilitypatterns/testador_BE4A33E7.html"];
contentPage.processPage.elementUrls["_haGrJJYlEeaRb6mrVBIJLA"] = ["Arquiteto","Enutri/capabilitypatterns/arquiteto_815DA2.html"];
contentPage.processPage.elementUrls["_qKbN4JX8Eea5INDw8_iX4w"] = ["Marco da Operação Inicial","Enutri/deliveryprocesses/Marco da_82B9E8C0.html"];
contentPage.processPage.elementUrls["_KljuYZX7Eea5INDw8_iX4w"] = ["Ciclo de Vida do Processo","Enutri/deliveryprocesses/Ciclo de Vida_D6739670.html"];
contentPage.processPage.elementUrls["_SboZUJYoEeaRb6mrVBIJLA_hX2FgJYeEeaRb6mrVBIJLA"] = ["Base de Conhecimento","Enutri/capabilitypatterns/conhecimento_70ACF1EE.html"];
contentPage.processPage.elementUrls["_hWhysJYlEeaRb6mrVBIJLA_5OUY8JX-Eea5INDw8_iX4w"] = ["Lista de Tarefas","Enutri/capabilitypatterns/tarefas_289B35F4.html"];
contentPage.processPage.elementUrls["_25ftQZYXEeaEjfH4fvjAEA"] = ["Arquitetura [Eb+1..Ec]","Enutri/deliveryprocesses/Arquitetura_ADD4E5E7.html"];
contentPage.processPage.elementUrls["_T8rZUZX8Eea5INDw8_iX4w"] = ["Planejar e Gerenciar a Iteração","Enutri/deliveryprocesses/Gerenciar a Iteração_D5BF8D35.html"];
contentPage.processPage.elementUrls["_SboZUJYoEeaRb6mrVBIJLA_toEHgJX-Eea5INDw8_iX4w"] = ["Stakeholder","Enutri/capabilitypatterns/stakeholder_84B169EA.html"];
contentPage.processPage.elementUrls["_6VlmY5YnEeaRb6mrVBIJLA"] = ["Realizar Tarefas Contínuas","Enutri/deliveryprocesses/Realizar Tarefas Contínuas_40344F3D.html"];
contentPage.processPage.elementUrls["_50vVMZX9Eea5INDw8_iX4w_oEOEcJX-Eea5INDw8_iX4w"] = ["Arquiteto","Enutri/capabilitypatterns/arquiteto_C6BF063F.html"];
contentPage.processPage.elementUrls["_fBMPoJX8Eea5INDw8_iX4w_oEOEcJX-Eea5INDw8_iX4w"] = ["Arquiteto","Enutri/capabilitypatterns/arquiteto_A5DB98E.html"];
contentPage.processPage.elementUrls["_9-3owZX8Eea5INDw8_iX4w"] = ["Planejar a Arquitetura","Enutri/deliveryprocesses/Desenvolver a Arquitetura_14989D77.html"];
contentPage.processPage.elementUrls["_5QfqkZX7Eea5INDw8_iX4w"] = ["Refinamento dos Requisitos [E1..Ea]","Enutri/deliveryprocesses/Refinamento dos Requisitos_EFE4ADD9.html"];
contentPage.processPage.elementUrls["_fBMPoJX8Eea5INDw8_iX4w_uqkGUJX-Eea5INDw8_iX4w"] = ["Testador","Enutri/capabilitypatterns/testador_8CD823A8.html"];
contentPage.processPage.elementUrls["_fBMPoJX8Eea5INDw8_iX4w_lXgyUJYZEeaEjfH4fvjAEA"] = ["Visão","Enutri/capabilitypatterns/visao_9A4B67A4.html"];
contentPage.processPage.elementUrls["_ZGX-0JfwEeaGraIkjYaOmA"] = ["Modelo de Domínio","Enutri/capabilitypatterns/dominio_863C1E74.html"];
contentPage.processPage.elementUrls["_yzrUIZYnEeaRb6mrVBIJLA"] = ["Planejar e Gerenciar a Iteração","Enutri/deliveryprocesses/Planejar e Gerenciar a Iteração_BFF77D55.html"];
contentPage.processPage.elementUrls["_4NF3YJX8Eea5INDw8_iX4w"] = ["Marco da Liberação do Produto","Enutri/deliveryprocesses/Marco da Liberação do Produto_FD113E1C.html"];
contentPage.processPage.elementUrls["_2SjlIJfwEeaGraIkjYaOmA"] = ["Banco de Dados de Produção","Enutri/capabilitypatterns/db_producao_3110ADDC.html"];
contentPage.processPage.elementUrls["_fBMPoJX8Eea5INDw8_iX4w_rpgJEJX-Eea5INDw8_iX4w"] = ["Gerente do projeto","Enutri/capabilitypatterns/gerente_6E07A821.html"];
contentPage.processPage.elementUrls["_AwwIcZYnEeaRb6mrVBIJLA"] = ["Desenvolver a Interface com o Usuário","Enutri/deliveryprocesses/Desenvolver a Interface com o Usuário_5E95BFF.html"];
contentPage.processPage.elementUrls["_fBMPoJX8Eea5INDw8_iX4w_wbLvYJX-Eea5INDw8_iX4w"] = ["Cronograma","Enutri/capabilitypatterns/cronograma_A4E3BBC1.html"];
contentPage.processPage.elementUrls["_4ATOAZX7Eea5INDw8_iX4w"] = ["Banco de Dados [Ea+1..Eb]","Enutri/deliveryprocesses/Banco de Dados_C5DE73C4.html"];
contentPage.processPage.elementUrls["_fBMPoJX8Eea5INDw8_iX4w_xjCvUJX-Eea5INDw8_iX4w"] = ["Plano do Projeto","Enutri/capabilitypatterns/projeto_plano_59391095.html"];
contentPage.processPage.elementUrls["_SboZUJYoEeaRb6mrVBIJLA_oQfbgJYiEeaRb6mrVBIJLA"] = ["Modelo de Casos de Uso","Enutri/capabilitypatterns/uc_modelo_B9163B2C.html"];
contentPage.processPage.elementUrls["_dNIGcZX7Eea5INDw8_iX4w"] = ["Iteração de Construção [C1..Cn]","Enutri/deliveryprocesses/Iteração de Construção C1..Cn_5CCEAD22.html"];
contentPage.processPage.elementUrls["_lRGugJX8Eea5INDw8_iX4w"] = ["Marco dos Objetivos","Enutri/deliveryprocesses/Marco dos Objetivos_4A3F4EBB.html"];
contentPage.processPage.elementUrls["_U11rYZX7Eea5INDw8_iX4w"] = ["Transição","Enutri/deliveryprocesses/Transição_34646B81.html"];
contentPage.processPage.elementUrls["_9MPHYZX7Eea5INDw8_iX4w"] = ["Iteração de Elaboração [E1..En]","Enutri/deliveryprocesses/Iteração de Elaboração E1..En_2D23C810.html"];
contentPage.processPage.elementUrls["_yzrUI5YnEeaRb6mrVBIJLA"] = ["Realizar Tarefas Contínuas","Enutri/deliveryprocesses/Realizar Tarefas Contínuas_176A6730.html"];
contentPage.processPage.elementUrls["_SboZUJYoEeaRb6mrVBIJLA_moV8UJX-Eea5INDw8_iX4w"] = ["Analista","Enutri/capabilitypatterns/analista_8BE089A2.html"];
contentPage.processPage.elementUrls["_6iCK8ZX7Eea5INDw8_iX4w"] = ["Interface com o Usuário [Ec+1..Ed]","Enutri/deliveryprocesses/Interface com o Usuário_49468EC0.html"];
contentPage.processPage.elementUrls["_dOhQ8JYkEeaRb6mrVBIJLA"] = ["Plano de Iteração","Enutri/capabilitypatterns/iteracao_plano_3071E803.html"];
contentPage.processPage.elementUrls["_znprkpYjEeaRb6mrVBIJLA"] = ["Desenvolvedor","Enutri/capabilitypatterns/desenvolvedor_CEE68F37.html"];
contentPage.processPage.elementUrls["_fBMPoJX8Eea5INDw8_iX4w_0LCFQJX-Eea5INDw8_iX4w"] = ["Plano de Iteração","Enutri/capabilitypatterns/iteracao_plano_6775F213.html"];
contentPage.processPage.elementUrls["_fBMPoZX8Eea5INDw8_iX4w_5OUY8JX-Eea5INDw8_iX4w"] = ["Lista de Tarefas","Enutri/capabilitypatterns/tarefas_FA83C49B.html"];
contentPage.processPage.elementUrls["_haGrJpYlEeaRb6mrVBIJLA"] = ["Desenvolvedor","Enutri/capabilitypatterns/desenvolvedor_F9B851C8.html"];
contentPage.processPage.elementUrls["_SboZUJYoEeaRb6mrVBIJLA"] = ["Descrever a Arquitetura","Enutri/capabilitypatterns/arquitetura_descrever_6D494EF0.html"];
contentPage.processPage.elementUrls["_SboZUJYoEeaRb6mrVBIJLA_lXgyUJYZEeaEjfH4fvjAEA"] = ["Visão","Enutri/capabilitypatterns/visao_F3F5DDB2.html"];
contentPage.processPage.elementUrls["_fBMPoZX8Eea5INDw8_iX4w"] = ["Gerenciar a Iteração","Enutri/capabilitypatterns/iteracao_gerenciar_3CE56D4E.html"];
contentPage.processPage.elementUrls["_dNU-IJYkEeaRb6mrVBIJLA"] = ["Refinar os Requisitos","Enutri/capabilitypatterns/requisitos_refinar_14904E60.html"];
contentPage.processPage.elementUrls["_zn8mgJYjEeaRb6mrVBIJLA"] = ["Especificação de Caso de Uso","Enutri/capabilitypatterns/uc_especificacao_13AD4508.html"];
contentPage.processPage.elementUrls["_lw2-EJYnEeaRb6mrVBIJLA"] = ["Implementar","Enutri/capabilitypatterns/Implementar_9D67DC4B.html"];
contentPage.processPage.elementUrls["_znzclJYjEeaRb6mrVBIJLA"] = ["Lista de Tarefas","Enutri/capabilitypatterns/tarefas_99982297.html"];
contentPage.processPage.elementUrls["_6VlmZZYnEeaRb6mrVBIJLA"] = ["Treinar Usuários","Enutri/deliveryprocesses/Treinar Usuários_AD534781.html"];
contentPage.processPage.elementUrls["_A0unUZYYEeaEjfH4fvjAEA"] = ["Desenvolver o Banco de Dados","Enutri/deliveryprocesses/Desenvolver o Banco de Dados_7D4E417B.html"];
contentPage.processPage.elementUrls["_x0pgEZYnEeaRb6mrVBIJLA"] = ["Implantar Sistema","Enutri/deliveryprocesses/Implantar Sistema_29AA75C4.html"];
contentPage.processPage.elementUrls["_ZFem8pfwEeaGraIkjYaOmA"] = ["Arquiteto","Enutri/capabilitypatterns/arquiteto_C5398124.html"];
contentPage.processPage.elementUrls["_L_R2YZYnEeaRb6mrVBIJLA"] = ["Planejar a Construção","Enutri/deliveryprocesses/Planejar a Construção_FCEBC374.html"];
contentPage.processPage.elementUrls["_Dc2iU5YnEeaRb6mrVBIJLA"] = ["Realizar Tarefas Contínuas","Enutri/deliveryprocesses/Realizar Tarefas Contínuas_7BAD5A76.html"];
contentPage.processPage.elementUrls["_WVEpgZX7Eea5INDw8_iX4w"] = ["Implantação [T1..Ta]","Enutri/deliveryprocesses/Implantação_50D5B600.html"];
contentPage.processPage.elementUrls["_znWwoJYjEeaRb6mrVBIJLA"] = ["Analista","Enutri/capabilitypatterns/analista_4D7D1D0B.html"];
contentPage.processPage.elementUrls["_zm6EsJYjEeaRb6mrVBIJLA_-5MVsJfuEeaGraIkjYaOmA"] = ["Modelo de Domínio","Enutri/capabilitypatterns/dominio_49DB29.html"];
contentPage.processPage.elementUrls["_Csus85YnEeaRb6mrVBIJLA"] = ["Realizar Tarefas Contínuas","Enutri/deliveryprocesses/Realizar Tarefas Contínuas_223346CB.html"];
contentPage.processPage.elementUrls["_ZFem8JfwEeaGraIkjYaOmA"] = ["Analista","Enutri/capabilitypatterns/analista_CC028CFE.html"];
contentPage.processPage.elementUrls["_fBMPopX8Eea5INDw8_iX4w_-RtaUJX-Eea5INDw8_iX4w"] = ["Documento da Arquitetura","Enutri/capabilitypatterns/arquitetura_2726245C.html"];
contentPage.processPage.elementUrls["_50vVMZX9Eea5INDw8_iX4w"] = ["Definir a Visão","Enutri/capabilitypatterns/visao_definir_C3F073AD.html"];
contentPage.processPage.elementUrls["_znzckJYjEeaRb6mrVBIJLA"] = ["Base de Conhecimento","Enutri/capabilitypatterns/conhecimento_D5064078.html"];
contentPage.processPage.elementUrls["_fBMPopX8Eea5INDw8_iX4w"] = ["Planejar a Iteração","Enutri/capabilitypatterns/iteracao_planejar_2B7E8164.html"];
contentPage.processPage.elementUrls["_mktrcJX8Eea5INDw8_iX4w"] = ["Marco da Arquitetura","Enutri/deliveryprocesses/Marco da Arquitetura_47E103E7.html"];
contentPage.processPage.elementUrls["_50vVMJX9Eea5INDw8_iX4w_xjCvUJX-Eea5INDw8_iX4w"] = ["Plano do Projeto","Enutri/capabilitypatterns/projeto_plano_A3BB4F56.html"];
contentPage.processPage.elementUrls["_SboZUJYoEeaRb6mrVBIJLA_-RtaUJX-Eea5INDw8_iX4w"] = ["Documento da Arquitetura","Enutri/capabilitypatterns/arquitetura_925ED950.html"];
contentPage.processPage.elementUrls["_-jchMZYXEeaEjfH4fvjAEA"] = ["Gerenciar os Requisitos","Enutri/deliveryprocesses/Gerenciar os Requisitos_3BB973DC.html"];
contentPage.processPage.elementUrls["_Csus8ZYnEeaRb6mrVBIJLA"] = ["Planejar e Gerenciar a Iteração","Enutri/deliveryprocesses/Planejar e Gerenciar a Iteração_CAC05CF0.html"];
contentPage.processPage.elementUrls["_HFKs05YnEeaRb6mrVBIJLA"] = ["Realizar Tarefas Contínuas","Enutri/deliveryprocesses/Realizar Tarefas Contínuas_66D087AB.html"];
contentPage.processPage.elementUrls["_OkY3cZYnEeaRb6mrVBIJLA"] = ["Implementar","Enutri/deliveryprocesses/Desenvolver Incremento_F87288ED.html"];
contentPage.processPage.elementUrls["_7tUSUZX7Eea5INDw8_iX4w"] = ["Planejamento da Construção [Ec+1..Ee]","Enutri/deliveryprocesses/Planejamento da Construção_55999423.html"];
contentPage.processPage.elementUrls["_haGrKJYlEeaRb6mrVBIJLA"] = ["Stakeholder","Enutri/capabilitypatterns/stakeholder_C5133FC1.html"];
contentPage.processPage.elementUrls["_SWNAMZX7Eea5INDw8_iX4w"] = ["Concepção","Enutri/deliveryprocesses/Elaboração_AEEF60C7.html"];
contentPage.processPage.elementUrls["_50vVMZX9Eea5INDw8_iX4w_lXgyUJYZEeaEjfH4fvjAEA"] = ["Visão","Enutri/capabilitypatterns/visao_56ACB455.html"];
contentPage.processPage.elementUrls["_ZGq5wJfwEeaGraIkjYaOmA"] = ["Modelo Lógico do Banco de Dados","Enutri/capabilitypatterns/db_logico_16D2D25C.html"];
contentPage.processPage.elementUrls["_50vVMZX9Eea5INDw8_iX4w_hX2FgJYeEeaRb6mrVBIJLA"] = ["Base de Conhecimento","Enutri/capabilitypatterns/conhecimento_D363C891.html"];
contentPage.processPage.elementUrls["_TPexkZX7Eea5INDw8_iX4w"] = ["Elaboração","Enutri/deliveryprocesses/Concepção_E5842781.html"];
contentPage.processPage.elementUrls["_XOL8oZYYEeaEjfH4fvjAEA"] = ["Realizar Tarefas Contínuas","Enutri/deliveryprocesses/Manter Tarefas Contínuas_95CCC39C.html"];
contentPage.processPage.elementUrls["_HwUtMJYoEeaRb6mrVBIJLA"] = ["Treinar os Usuários","Enutri/capabilitypatterns/treinar_E66584AC.html"];
contentPage.processPage.elementUrls["_81LBgZYXEeaEjfH4fvjAEA"] = ["Planejar e Gerenciar a Iteração","Enutri/deliveryprocesses/Gerenciar a Iteração_D56600EF.html"];
contentPage.processPage.elementUrls["_1o_1UZfxEeaGraIkjYaOmA"] = ["Realizar Tarefas Contínuas","Enutri/deliveryprocesses/Realizar Tarefas Contínuas_4C5CF38E.html"];
contentPage.processPage.elementUrls["_50vVMZX9Eea5INDw8_iX4w_toEHgJX-Eea5INDw8_iX4w"] = ["Stakeholder","Enutri/capabilitypatterns/stakeholder_E768408D.html"];
contentPage.processPage.elementUrls["_haGrIpYlEeaRb6mrVBIJLA"] = ["Analista","Enutri/capabilitypatterns/analista_35266FA9.html"];
contentPage.processPage.elementUrls["_50vVMJX9Eea5INDw8_iX4w_uqkGUJX-Eea5INDw8_iX4w"] = ["Testador","Enutri/capabilitypatterns/testador_D75A6269.html"];
contentPage.processPage.elementUrls["_zm6EsJYjEeaRb6mrVBIJLA"] = ["Capturar e Descrever os Requisitos","Enutri/capabilitypatterns/requisitos_capturar_4C07F615.html"];
contentPage.processPage.elementUrls["_Q0obwZYnEeaRb6mrVBIJLA"] = ["Planejar e Gerenciar a Iteração","Enutri/deliveryprocesses/Planejar e Gerenciar a Iteração_23D37275.html"];
contentPage.processPage.elementUrls["_liGqQJfxEeaGraIkjYaOmA"] = ["Visão","Enutri/deliveryprocesses/visao_982023F9.html"];
contentPage.processPage.elementUrls["_ZGhIwJfwEeaGraIkjYaOmA"] = ["Modelo de Casos de Uso","Enutri/capabilitypatterns/uc_modelo_371EC19.html"];
contentPage.processPage.elementUrls["_zoGXgpYjEeaRb6mrVBIJLA"] = ["Requisitos Suplementares","Enutri/capabilitypatterns/requisitos_suplementares_CCFEB96B.html"];
contentPage.processPage.elementUrls["_WythkZYYEeaEjfH4fvjAEA"] = ["Realizar Tarefas Contínuas","Enutri/deliveryprocesses/Manter Tarefas Contínuas_CF539AB3.html"];
contentPage.processPage.elementUrls["_ZGhIwpfwEeaGraIkjYaOmA"] = ["Visão","Enutri/capabilitypatterns/visao_FCA8E03F.html"];
contentPage.processPage.elementUrls["_fBMPoJX8Eea5INDw8_iX4w_pXuTsJX-Eea5INDw8_iX4w"] = ["Desenvolvedor","Enutri/capabilitypatterns/desenvolvedor_385D5B19.html"];
contentPage.processPage.elementUrls["_SboZUJYoEeaRb6mrVBIJLA_rpgJEJX-Eea5INDw8_iX4w"] = ["Gerente do projeto","Enutri/capabilitypatterns/gerente_C7B21E2F.html"];
contentPage.processPage.elementUrls["_fBMPoJX8Eea5INDw8_iX4w"] = ["Encerrar a Iteração","Enutri/capabilitypatterns/iteracao_encerrar_32478D3E.html"];
contentPage.processPage.elementUrls["_zoGXgJYjEeaRb6mrVBIJLA"] = ["Modelo de Casos de Uso","Enutri/capabilitypatterns/uc_modelo_D3C7C545.html"];
contentPage.processPage.elementUrls["_953a4ZYmEeaRb6mrVBIJLA"] = ["Desenvolver a Arquitetura","Enutri/deliveryprocesses/Desenvolver a Arquitetura_E2A486AF.html"];
contentPage.processPage.elementUrls["_znzckpYjEeaRb6mrVBIJLA"] = ["Visão","Enutri/capabilitypatterns/visao_CE3D349E.html"];
contentPage.processPage.elementUrls["_50vVMZX9Eea5INDw8_iX4w_rpgJEJX-Eea5INDw8_iX4w"] = ["Gerente do projeto","Enutri/capabilitypatterns/gerente_2A68F4D2.html"];
contentPage.processPage.elementUrls["_Dc2iUZYnEeaRb6mrVBIJLA"] = ["Planejar e Gerenciar a Iteração","Enutri/deliveryprocesses/Planejar e Gerenciar a Iteração_243A709B.html"];
contentPage.processPage.elementUrls["_EnzdEJYoEeaRb6mrVBIJLA"] = ["Elaborar o Manual do Usuário","Enutri/capabilitypatterns/manual_elaborar_5CA281F9.html"];
contentPage.processPage.elementUrls["_SboZUJYoEeaRb6mrVBIJLA_oEOEcJX-Eea5INDw8_iX4w"] = ["Arquiteto","Enutri/capabilitypatterns/arquiteto_64082F9C.html"];
contentPage.processPage.elementUrls["_hWhysJYlEeaRb6mrVBIJLA"] = ["Solicitar Mudança","Enutri/capabilitypatterns/mudanca_solicitar_796A4C15.html"];
contentPage.processPage.elementUrls["_50vVMZX9Eea5INDw8_iX4w_5OUY8JX-Eea5INDw8_iX4w"] = ["Lista de Tarefas","Enutri/capabilitypatterns/tarefas_4506035C.html"];
contentPage.processPage.elementUrls["_9S-zIZX8Eea5INDw8_iX4w"] = ["Iniciar o Projeto","Enutri/deliveryprocesses/Iniciar o Projeto_99D9A1C.html"];
contentPage.processPage.elementUrls["_SboZUJYoEeaRb6mrVBIJLA_pXuTsJX-Eea5INDw8_iX4w"] = ["Desenvolvedor","Enutri/capabilitypatterns/desenvolvedor_9207D127.html"];
contentPage.processPage.elementUrls["_ZDY8QJfwEeaGraIkjYaOmA"] = ["Modelar o Banco de Dados","Enutri/capabilitypatterns/db_modelar_75336D9A.html"];
contentPage.processPage.elementUrls["_50vVMZX9Eea5INDw8_iX4w_moV8UJX-Eea5INDw8_iX4w"] = ["Analista","Enutri/capabilitypatterns/analista_EE976045.html"];
contentPage.processPage.elementUrls["_iknrkJYnEeaRb6mrVBIJLA"] = ["Implementar","Enutri/capabilitypatterns/Implementar_592D5245.html"];
contentPage.processPage.elementUrls["_2SG5MJfwEeaGraIkjYaOmA"] = ["Implementar o Banco de Dados","Enutri/capabilitypatterns/db_implementar_689CE6E4.html"];
contentPage.processPage.elementUrls["_XkzzEZX7Eea5INDw8_iX4w"] = ["Treinamento [Ta+1..Tb]","Enutri/deliveryprocesses/Treinamento_C1B0BF4B.html"];
contentPage.processPage.elementUrls["_50vVMJX9Eea5INDw8_iX4w"] = ["Planejar o Projeto","Enutri/capabilitypatterns/projeto_planejar_B952939D.html"];
contentPage.processPage.elementUrls["_DWQv8ZYYEeaEjfH4fvjAEA"] = ["Planejar e Gerenciar a Iteração","Enutri/deliveryprocesses/Gerenciar a Iteração_92372328.html"];
contentPage.processPage.elementUrls["_T3pk0ZX7Eea5INDw8_iX4w"] = ["Construção","Enutri/deliveryprocesses/Construção_ACDE7A07.html"];
