<?php

/**
 * Classes CSS para a padronização dos ícones da aplicação
 * 
 * @author Renato Uchoa <contato@renatouchoa.com.br>
 */
return [
    'Icons' => [
        'ajuda'         => 'fa fa-fw fa-file',
        'alert-danger'  => 'fa fa-fw fa-ban',
        'alert-warning' => 'fa fa-fw fa-warning',
        'alert-info'    => 'fa fa-fw fa-info',
        'alert-success' => 'fa fa-fw fa-check',
        'alimento'      => 'fa fa-fw fa-apple',
        'aprovar'       => 'fa fa-fw fa-thumbs-o-up',
        'atendimento'   => 'fa fa-fw fa-calendar',
        'avaliar'       => 'fa fa-fw fa-eye',
        'cadastrar'     => 'fa fa-fw fa-plus',
        'cancelar'      => 'fa fa-fw fa-times',
        'cardapio'      => 'fa fa-fw fa-cutlery',
        'centralizacao' => 'fa fa-fw fa-sitemap fa-rotate-180',
        'editar'        => 'fa fa-fw fa-pencil',
        'eex'           => 'fa fa-fw fa-building',
        'estatistica'   => 'fa fa-fw fa-bar-chart',
        'excluir'       => 'fa fa-fw fa-trash-o',
        'exercicio'     => 'fa fa-fw fa-circle-o-notch',
        'externo'       => 'fa fa-fw fa-external-link mini',
        'form'          => 'fa fa-fw fa-edit',
        'imprimir'      => 'fa fa-fw fa-print',
        'info'          => 'fa fa-fw fa-info-circle',
        'ingrediente'   => 'fa fa-fw fa-apple',
        'inserir'       => 'fa fa-fw fa-indent',
        'lista'         => 'fa fa-fw fa-list',
        'logout'        => 'fa fa-fw fa-power-off',
        'manual'        => 'fa fa-fw fa-book',
        'novo'          => 'fa fa-fw fa-plus',
        'nutriente'     => 'fa fa-fw fa-heartbeat',
        'painel'        => 'fa fa-fw fa-th-large',
        'planejamento'  => 'fa fa-fw fa-file',
        'preparacao'    => 'fa fa-fw fa-cutlery',
        'processo'      => 'fa fa-fw fa-folder',
        'processos'     => 'fa fa-fw fa-folder',
        'prosseguir'    => 'fa fa-fw fa-arrow-right',
        'referencia'    => 'fa fa-fw fa-percent',
        'relatorio'     => 'fa fa-fw fa-file-text-o',
        'remover'       => 'fa fa-fw fa-outdent',
        'reprovar'      => 'fa fa-fw fa-thumbs-o-down',
        'salvar'        => 'fa fa-fw fa-check-circle',
        'senha'         => 'fa fa-fw fa-asterisk',
        'sobre'         => 'fa fa-fw fa-info-circle',
        'uex'           => 'fa fa-fw fa-home',
        'usuario'       => 'fa fa-fw fa-user',
        'usuarios'      => 'fa fa-fw fa-users',
        'visualizar'    => 'fa fa-fw fa-info-circle',
        'voltar'        => 'fa fa-fw fa-arrow-left',
    ],
];
